apiVersion: v1
kind: Pod
metadata:
  name: kube-addon-manager
  namespace: kube-system
  labels:
    component: kube-addon-manager
    version: v4
spec:
  hostNetwork: true
  containers:
  - name: kube-addon-manager
    # When updating version also bump it in cluster/images/hyperkube/static-pods/addon-manager.json
    image: siriuszg/kube-addon-manager:v5.2
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
    volumeMounts:
    - mountPath: /etc/kubernetes/
      name: addons
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/
    name: addons